"""Add word knowledge rating

Revision ID: 1b47f3707523
Revises: 6f64c4f48a35
Create Date: 2022-11-20 15:48:25.569605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b47f3707523'
down_revision = '6f64c4f48a35'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dictionary_content', sa.Column('word_knowledge', sa.Integer(), server_default='0', default=0))
    op.add_column('user_translation', sa.Column('word_knowledge', sa.Integer(), server_default='0', default=0))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_translation', 'word_knowledge')
    op.drop_column('dictionary_content', 'word_knowledge')
    # ### end Alembic commands ###
