"""Definition add

Revision ID: 3454de135531
Revises: e6070f2fcb70
Create Date: 2022-09-10 19:00:19.063497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3454de135531'
down_revision = 'e6070f2fcb70'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('definition',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('phonetic', sa.String(), nullable=True),
    sa.Column('phonetics', sa.JSON(), nullable=True),
    sa.Column('origin', sa.String(), nullable=True),
    sa.Column('meanings', sa.JSON(), nullable=True),
    sa.Column('license', sa.JSON(), nullable=True),
    sa.Column('source_url', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('definition')
    # ### end Alembic commands ###
