"""Representation fields added

Revision ID: 6915b80a5336
Revises: 3454de135531
Create Date: 2022-09-10 23:49:10.412420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6915b80a5336'
down_revision = '3454de135531'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_translation', 'word', existing_type=sa.String, type_=sa.String(length=300), existing_nullable=False)
    op.alter_column('user_translation', 'translation', existing_type=sa.String, type_=sa.String(length=300), existing_nullable=False)
    op.add_column('user_translation', sa.Column('word_representation', sa.String(length=300)))
    op.add_column('user_translation', sa.Column('translation_representation', sa.String(length=300)))
    op.drop_constraint('uq_word_translation_uid', 'user_translation', type_='unique')
    op.create_unique_constraint('uq_word_translation_uid', 'user_translation', ['word', 'word_representation', 'translation', 'translation_representation', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_translation', 'word', existing_type=sa.String(length=300), type_=sa.String, existing_nullable=False)
    op.alter_column('user_translation', 'translation', existing_type=sa.String(length=300), type_=sa.String, existing_nullable=False)
    op.create_unique_constraint('uq_word_translation_uid', 'user_translation', ['word', 'translation', 'user_id'])
    op.drop_column('user_translation', 'translation_representation')
    op.drop_column('user_translation', 'word_representation')
    # ### end Alembic commands ###
