"""Unique constraint on dictionary content

Revision ID: 6f64c4f48a35
Revises: e44677a8c1da
Create Date: 2022-09-11 20:15:19.619424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f64c4f48a35'
down_revision = 'e44677a8c1da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "dictionary_content", ["dictionary_id", "word", "translation"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dictionary_content', type_='unique')
    # ### end Alembic commands ###
