"""Urban dictionary add

Revision ID: 8d094425c5a4
Revises: 493cb6086514
Create Date: 2022-09-07 22:23:48.199158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d094425c5a4'
down_revision = '493cb6086514'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
