"""Representation field not null

Revision ID: b4bc3fd55f1f
Revises: 6915b80a5336
Create Date: 2022-09-11 00:09:30.959416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4bc3fd55f1f'
down_revision = '6915b80a5336'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_translation', 'word_representation', nullable=False, existing_nullable=True)
    op.alter_column('user_translation', 'translation_representation', nullable=False, existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_translation', 'word_representation', nullable=True, existing_nullable=False)
    op.alter_column('user_translation', 'translation_representation', nullable=True, existing_nullable=False)
    # ### end Alembic commands ###
