"""User state data datetype changed to JSON

Revision ID: e44677a8c1da
Revises: 66faa7e1a6e3
Create Date: 2022-09-11 19:54:12.074931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e44677a8c1da'
down_revision = '66faa7e1a6e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'dictionary', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dictionary', type_='unique')
    # ### end Alembic commands ###
