"""restrict duplicate translations

Revision ID: e6070f2fcb70
Revises: fd00a9a85aea
Create Date: 2022-09-08 00:15:09.088653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6070f2fcb70'
down_revision = 'fd00a9a85aea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_word_translation_uid', 'user_translation', ['word', 'translation', 'user_id'], schema='public')
    op.create_unique_constraint('uq_defid_word', 'urban_dictionary', ['word', 'defid'], schema='public')
    op.create_unique_constraint('uc_user_id_dictionary_id', 'users_dictionaries', ['user_id', 'dictionary_id'], schema='public')
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_word_translation_uid', 'user_translation')
    op.drop_constraint('uq_defid_word', 'urban_dictionary')
    op.drop_constraint('uc_user_id_dictionary_id', 'users_dictionaries')
    pass
    # ### end Alembic commands ###
