"""Urban dictionary add

Revision ID: fd00a9a85aea
Revises: 493cb6086514
Create Date: 2022-09-07 22:34:38.304457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd00a9a85aea'
down_revision = '493cb6086514'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urban_dictionary',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('defid', sa.String(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('permalink', sa.String(), nullable=False),
    sa.Column('definition', sa.String(), nullable=True),
    sa.Column('example', sa.String(), nullable=True),
    sa.Column('votes', sa.JSON(), nullable=True),
    sa.Column('current_vote', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('urban_dictionary')
    # ### end Alembic commands ###
